### ISSUE TITLE
4/17

### ISSUE THREAD

**Issue by Kosuke0820** [Kosuke0820/gs_academy_final_products_Snug#2]
お疲れ様です。

無事作り終えました！フォロー機能が間に合わなかった点が悲しいですが。。

デプロイはFirebaseにしました。
一応URL共有させて頂きます。
https://snug-45a34.firebaseapp.com/
iosのテストフライトもできまして、アドレス頂ければお送りしますので宜しくお願い致します。

そして、お聞きしたことがあるのですが、

①画像サイズに関して
iosアプリで4G回線の際の画像の読み込みに時間がかかってしまいまして。。
特に投稿画像一覧ページのサムネイル(約12枚ほど読み込み)で時間がかかります。
実際の現場だとやはりサムネイル用に圧縮した画像を別で使うのでしょうか？
ちなみにレイジーロードは実装しました！

あと初歩的な事かもしれませんが、Firebaseからデータを引っ張ってきた後、その画像のURLにロードしにいって読み込みが終わるまでの間の処理はどんな方法があるのでしょうか？

②今回スタイリングはSassを使いましたが、現場でCSS in JS の手法などは使われる事多いのでしょうか？　もちろんプロジェクトによってまちまちだとは思いますが参考までにお聞きしておきたいと思いました。

今回はもう間に合わないので実装はできませんが、知っておきたい内容であった為宜しくお願い致します。

発表がいよいよ明後日です！
プレゼン資料作り上げます！

**Comment by herablog** [comment]
お疲れさまでした〜！

もう少し動きも見させてもらいたいので、TestFlightを`kz.route21@gmail.com` でお願いします〜。
あと、Webのログインはどんな感じだろ？

> ①画像サイズに関して

クライアントサイドでできることとしては、Lazy Load実装できたのはバッチリだね！画像の処理は何パターンかあって、[imgix](https://www.imgix.com/)とか[Image Manager](https://www.akamai.com/jp/ja/products/web-performance/image-manager.jsp)とか使ってリアルタイムに変換する方法とか、あらかじめ表示サイズがある程度決まっている場合には、画像のアップロード時に何種類か変換しておくっていうのがあるかな。Firebaseの場合は、Cloud Functionと[ImageMagick](https://ja.wikipedia.org/wiki/ImageMagick)使って、[リサイズするサンプル](https://github.com/firebase/functions-samples/tree/master/image-sharp)がこんな感じであるよ。

ImageMagickはいろんな変換オプションがあるので、ある程度やりたいことはできそう。

> Firebaseからデータを引っ張ってきた後、その画像のURLにロードしにいって読み込みが終わるまでの間の処理

これは、どうゆうことだろう。画像が読み込み終わるまでplaceholderを表示しておくとかそうゆうことかな？

> スタイリング

これは、かなりプロジェクトによって変わっちゃうかも。どんな人が作っていくかにも結構よるよね。CSS得意な人がいる場合は、Sass + BEMとかで従来通りのパターンもあるし、React native共存だとCSS in JSとか, [styled-components/styled-components](https://github.com/styled-components/styled-components)もあるし、[css-modules/css-modules](https://github.com/css-modules/css-modules)もあるかな！うちの会社だとWeb専門が殆どで、postcss + CSS Modulesが今のところ人気かも。

ちなみに、Firebaseどうだった？

ひとまずは、プレゼン頑張ってね！！
質問は、プレゼン後でも受け付けます！

**Comment by Kosuke0820** [comment]
ご返信ありがとうございます！

テストフライト先ほどお送りしましたのでご確認宜しくお願い致します。
挙動おかしい部分多いと思いますが。。。
ちなみに画像が圧縮比率あげすぎてあげるとめちゃくちゃ画質悪いです。
先ほど改善してもう一度テストフライト審査出してますので、ご了承ください。。

これが各種ログイン情報です。
[WEB] 
(email) - testShop@gmail.com
(pass) - 123456

[ios] 
(email) - testUser@gmail.com
(pass) - 123456

> 画像の処理は何パターンかあって、imgixとかImage Managerとか
こんな手法があるんですね！
全く知らなかったです。。

> Firebaseからデータを引っ張ってきた後、その画像のURLにロードしにいって読み込みが終わるまでの間の処理
そうです！placeholderでローディング中がわかるような実装にしたかったのですが、調べてもわかりませんでした。。。

> スタイリング
そんな色々と種類があるんですね！
確かに今回なんかはiosもwebもViewが似てるのでCSS in JSでもよかったのかもしれませんね。。

> Firebase
Firebaseよかったです！
Node + Mongoでやってたらおそらくここまで終わっていなかったです。笑
cloud messagingとcloud functionsのおかげで思ってたより簡単にプッシュ通知実装できました！
ただ、データベースでワイルドカードなどやりたいクエリがなくてで結構ハマりました。。。

そう言っていただけると心強いです。ありがとうございます。
早く現場で働いて原さんに少しでも近づけるよう頑張りますー！

**Comment by herablog** [comment]
ありがとう！ちょいあとでゆっくり見させてもらうね！

とりあえずはプレゼンすぐだよね、準備頑張ってね！ちょいと予定合わずで行けなそうなんだけど、別で打ち上げはどうかな？

> placeholder

こうゆう感じかな？
https://jasonslyvia.github.io/react-lazyload/examples/#/placeholder?_k=yj9k7i

**Comment by Kosuke0820** [comment]
バタバタしておりました。。

そうです！
こんな感じでplaceholder入れたかったのですがこれもlazyloadでできそうですね！

昨日ようやくGGAが終了しました〜！
結果はこれからですが、とりあえずは目標までプロダクトを仕上げる事が出来て自信になりました！

是非お願いしたいです！！
来週からは卒業して就活に入りずっと暇してますので行きたいですー！
